### ISSUE TITLE
Peer中有多个的 AllowedIPs时只能保留最后一个

### ISSUE THREAD

**Issue by supernatural** [Rehtt/ini_lib_rust#1]
按Linux上man wg的说明：
       •      AllowedIPs — a comma-separated list of IP (v4 or v6) addresses with CIDR masks from which incoming traffic for this peer is allowed and to  which  outgoing  traffic for this peer is directed. The catch-all 0.0.0.0/0 may be specified for matching all IPv4 addresses, and ::/0 may be specified for matching all IPv6 addresses. May be specified multiple times.

'AllowedIPs' 可以在一个Peer段中出现多次，目前的实现会保留最后一个，丢弃其它的。

**Comment by Rehtt** [comment]
现在已经更新了
